name: Test & Deploy Web App
on:
  push:
    branches:
      - main

jobs:
  specs:
    runs-on: ubuntu-latest
     defaults:
      run:
        working-directory: app
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - uses: bahmutov/npm-install@v1

      - name: Run Tests
        run: test:ci
        env:
          CI: true

      - name: Deploy
        run: build:deploy
